alias rm='rm -v'
alias disku="du -sh * | sort -rn | head"
#alias search="apt-cache search"
#alias install="sudo apt-get install"
#alias remove="sudo apt-get remove"
#alias autoremove="sudo apt-get autoremove"
alias update="sudo apt-get update && sudo apt-get upgrade && sudo apt-get dist-upgrade"
#alias go="gnome-open"
alias wget="wget -c"
#alias handbrake="cd ~ && HandBrakeCLI"
#alias email="fetchmail ; mutt"
#alias music="mp3blaster"
#alias web="sudo links2 -g"
alias reboot="sudo reboot"
alias restart="sudo shutdown -r now"
alias a2reload="sudo service apache2 reload"
alias ping="ping -c 4"
alias pwe="ping -c 4 weinraub.com"
alias svnaddall="svn st --ignore-externals | grep ^? | sed 's/\?/svn add/' | sh"

alias pyson="python -mjson.tool"
alias qc="~/Scripts/qc/qc/qc.sh"
alias vbm="VBoxManage"

